import jwtHeader from './jwtHeader';
import loading from './loading';
import prevCancel from './prevCancel';
import registApi from './registApi';
import retry from './retry';
import catchError from './catchError';
export declare const axiosJWTHeader: typeof jwtHeader;
export declare const axiosLoading: typeof loading;
export declare const axiosPrevCancel: typeof prevCancel;
export declare const axiosRegistApi: typeof registApi;
export declare const axiosRetry: typeof retry;
export declare const axiosCatchError: typeof catchError;
